Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Kursinis.Data;

namespace Kursinis.Models
{
    public class ShoppingCart
    {
		private readonly ApplicationDbContext _context;

		public ShoppingCart(ApplicationDbContext context)
		{
			_context = context;
		}

		public string Id { get; set; }
		public IEnumerable<CartItem> ShoppingCartItems { get; set; }

		public static ShoppingCart GetCart(IServiceProvider services)
		{
			ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
			var context = services.GetService<ApplicationDbContext>();
			string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

			session.SetString("CartId", cartId);
			return new ShoppingCart(context) { Id = cartId };
		}

		public bool AddToCart(Products products, int amount)
		{
			
			var shoppingCartItem = _context.ShoppingCartItems.SingleOrDefault(
				s => s.Products.Id == products.Id && s.ShoppingCartId == Id);
			var isValidAmount = true;
			if (shoppingCartItem == null)
			{
				if (amount >= 0)
				{
					isValidAmount = true;
				}
				shoppingCartItem = new CartItem
				{
					ShoppingCartId = Id,
					Products = products,
					Amount = (amount)
				};
				
				_context.ShoppingCartItems.Add(shoppingCartItem);
			}
			else
			{
				if (shoppingCartItem.Amount - amount >= 0)
				{
					shoppingCartItem.Amount += amount;
				}
				else
				{
					shoppingCartItem.Amount += (shoppingCartItem.Amount);
					isValidAmount = true;
				}
			}


			_context.SaveChanges();
			return isValidAmount;
		}
		//neveikia velnias
		public int RemoveFromCart(Products products)
		{
			var shoppingCartItem = _context.ShoppingCartItems.SingleOrDefault(
				s => s.Products.Id == products.Id && s.ShoppingCartId == Id);
			int localAmount = 0;
			if (shoppingCartItem != null)
			{
				if (shoppingCartItem.Amount > 1)
				{
					shoppingCartItem.Amount--;
					localAmount = shoppingCartItem.Amount;
				}
				else
				{
					_context.ShoppingCartItems.Remove(shoppingCartItem);
				}
				_context.SaveChanges();
			}

			
			return localAmount;
		}

		public IEnumerable<CartItem> GetShoppingCartItems()
		{
			return ShoppingCartItems ??
				   (ShoppingCartItems = _context.ShoppingCartItems.Where(c => c.ShoppingCartId == Id)
					   .Include(s => s.Products));
		}

		public void ClearCart()
		{
			var cartItems = _context
				.ShoppingCartItems
				.Where(cart => cart.ShoppingCartId == Id);
			foreach (var cartItem in cartItems)
            {
				_context.ShoppingCartItems.RemoveRange(cartItem);
			}

			_context.SaveChanges();
		}

		public decimal GetShoppingCartTotal()
		{
			return _context.ShoppingCartItems.Where(c => c.ShoppingCartId == Id)
				.Select(c => c.Products.Price * c.Amount).Sum();
		}

		
	}
}

Controllers/OrderController.cs
using Kursinis.Data;

using Kursinis.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kursinis.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        
        private readonly IProducts _productService;
        private readonly IOrder _orderService;
        private readonly ShoppingCart _shoppingCart;
        public readonly UserManager<AppUser> _userManager;




        public OrderController(IOrder orderService, IProducts productService, ShoppingCart shoppingCart, UserManager<AppUser> userManager)
        {
            _orderService = orderService;
            _shoppingCart = shoppingCart;
            _productService = productService;
            _userManager = userManager;

        }

        public IActionResult Checkout()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some items first");
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public Order OrderIndexModelToOrder(OrderIndexModel model, AppUser user)
        {
            return new Order
            {
                Id = model.Id,
                OrderPlaced = model.OrderPlaced,
                OrderTotal = model.OrderTotal,
                Address = model.Address,
                City = model.City,
                Country = model.Country,
                ZipCode = model.ZipCode,
                //OrderLines = OrderDetailsListingModelToOrderDetails(model.OrderLines)
            };
        }


        
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderIndexModel model)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some items first");
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var user = await _userManager.FindByIdAsync(userId);

                model.OrderTotal = items.Sum(item => item.Amount * item.Products.Price);
                var order = OrderIndexModelToOrder(model, user);

                _orderService.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(model);
        }


        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order";
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kursinis.Data;
using Kursinis.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace Kursinis.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IProducts _productService;
        private readonly ShoppingCart _shoppingCart;
       

        public ShoppingCartController(IProducts productService, ShoppingCart shoppingCart)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Index(bool isValidAmount = true, string returnUrl = "/")
        {
            _shoppingCart.GetShoppingCartItems();

            var model = new ShoppingCartIndexModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
                ReturnUrl = returnUrl
            };

            if (!isValidAmount)
            {
                ViewBag.InvalidAmountText = "*There were not enough items in stock to add*";
            }

            return View("Index", model);
        }

        [HttpGet]
        [Route("/ShoppingCart/Add/{id}/{returnUrl?}")]
        public IActionResult Add(int id, int? amount = 1, string returnUrl = null)
        {
            var products = _productService.GetById(id);
            returnUrl = returnUrl.Replace("%2F", "/");
            bool isValidAmount = true;
            if (products != null)
            {
                isValidAmount = _shoppingCart.AddToCart(products, amount.Value);
            }

            return Index(isValidAmount, returnUrl);
        }
        [HttpGet]
        [Route("/ShoppingCart/Remove/{id}/{returnUrl?}")]
        public IActionResult Remove(int productsId)
        {
            var products = _productService.GetById(productsId);
            if (products != null)
            {
                _shoppingCart.RemoveFromCart(products);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Back(string returnUrl = "/")
        {
            return Redirect(returnUrl);
        }

        

    }
}

Views/ShoppingCart/Default.cshtml
@model Kursinis.Models.ShoppingCartIndexModel

<a asp-area="" asp-controller="ShoppingCart" asp-action="Index" style="padding:5px;color: rgba(0,0,0,.7);text-decoration: none;">
    <i class="fas fa-shopping-cart fa-3x"></i>
    <span style="font-size:20px; text-align:center; margin:5px;">
        @Html.Raw(@Model.ShoppingCart.ShoppingCartItems.Count())
    </span>
</a>

Views/ShoppingCart/Index.cshtml
@model Kursinis.Models.ShoppingCartIndexModel
@using System.Globalization

<div class="row checkoutForm" style="margin-bottom:250px;">
    <div>
        <h2>
            Your shopping cart           
        </h2>
    </div>
    <table class="table table-hover table-stripped table-bordered">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Product</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left"><a class="btn btn-info" asp-controller="Products" asp-action="Index" asp-route-id="@line.Products.Id">@line.Products.ItemName</a></td>
                    <td class="text-right">@line.Products.Price.ToString("c", CultureInfo.CreateSpecificCulture("en-US"))</td>
                    <td class="text-right">
                        @((line.Amount * line.Products.Price).ToString("c",CultureInfo.CreateSpecificCulture("en-US")))
                    </td>
                    <td class="text-center"><button asp-controller="ShoppingCart" asp-action="Remove" asp-route-id="@line.Products.Id"> Remove</button></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @(Model.ShoppingCartTotal.ToString("c",CultureInfo.CreateSpecificCulture("en-US")))
                </td>
            </tr>
        </tfoot>
    </table>
    @if (ViewBag.InvalidAmountText != null)
    {
        <div>
            <p class="invalidAmount">@ViewBag.InvalidAmountText</p>
        </div>
    }
    <div>
        <a class="btn btn-back" asp-action="Back" asp-route-returnUrl="@Model.ReturnUrl">Back</a>
    </div>
    @if (Model.ShoppingCart.ShoppingCartItems.Count() != 0)
    {
        <div class="text-right" style="float:right">
            <div class="btn-group ">
                <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            </div>
        </div>
    }
    else
    {
        <p>Your cart is empty, add some items to order them</p>
    }
</div>